name: Move new issues into Triage

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: New bug issue
        uses: alex-page/github-project-automation-plus@v0.5.1
        if: github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'bug')
        with:
          project: Testboard
          column: To assign
          repo-token: ${{ secrets.Test }}
          action: update

      - name: Bug label removed
        uses: alex-page/github-project-automation-plus@v0.5.1
        if: github.event.action == 'unlabeled'
        with:
          action: delete
          project: Testboard
          column: To assign
          repo-token: ${{ secrets.Test }}
          
